# The machine service deployment creates the Pods that run the machine services. The number of machine services created
# is defined via the replicas setting. You can deploy this configuration to the cluster with the command
#   kubectl apply -f machine-service.yml
# Notice that the image name is pulled from a hosted repository, you will not be able to build containers on the cluster
# and you will also notice that the mongo database is referred by name, which it will get from the service name defined
# in the mongo.yml
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: machine-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: machine-service
  template:
    metadata:
      labels:
        app: machine-service
    spec:
      containers:
      - name: machine-service
        image: stevenandrewcarter/machine_service:latest
        env:
        - name: MONGODB
          value: mongo
