apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: stevenandrewcarter/web_server:latest
        env:
        - name: MONGODB
          value: 10.0.0.6
        ports:
          - containerPort: 8080
