# The Web Server deployment will create and manage the Pods for the Web Server. It like the machine serices will need
# to set the MongoDB value as well. In addition the Web Server will require a Service so that it can be exposed outside
# of the Cluster.
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: stevenandrewcarter/web_server:latest
        env:
        - name: MONGODB
          value: mongo
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: web-server
  type: LoadBalancer
