---
version: '3'
services:
  mongo:
    image: "mongo"

  machine_service:
    image: stevenandrewcarter/machine_service
    depends_on:
      - mongo
    deploy:
      mode: replicated
      replicas: 5

  web_server:
    image: stevenandrewcarter/web_server
    depends_on:
      - mongo
      - machine_service
    ports: ['8080:8080']
