# Indicates the base image that the image will use
FROM node:alpine
# Which ports are exposed from the container
EXPOSE 8080
# Copy across local files to the container
COPY server.js .
# What command is executed on to start the application
CMD node server.js
